import {Layout} from "antd";
import Head from "next/head";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import {Fragment, useState, useEffect} from "react";
import {Page404} from "@/components/404";
import {useSelector, useDispatch} from "react-redux";
import {login, logout} from "@/store/slice/user";
import {useRouter} from "next/router";

const PageLayout = ({children, title = ''}) => {
 const [mobileNavsidebar, setMobileNavsidebar] = useState(false);
 const [users, setUsers] = useState(false);
 const {Content} = Layout;
 const dispatch = useDispatch();
 const router = useRouter();

 useEffect(() => {
  const user = JSON.parse(localStorage.getItem('data'))
  if (user) {
   setUsers(true)
   dispatch(login(user))
  } else {
   setUsers(false)
   dispatch(logout())
   localStorage.removeItem('data')
   router.push('/login')
  }
 }, [])

 return (
  <Fragment>
   {users ? (
    <Layout>
     <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by Curly"/>
      <link rel="icon" href="/favicon.ico"/>
     </Head>

     <div className="flex bg-gray-100 min-vh-100 relative">

      <Sidebar mobileNavsidebar={mobileNavsidebar}/>

      <div className="flex-grow text-gray-800">
       <Header mobileNavsidebar={mobileNavsidebar} setMobileNavsidebar={setMobileNavsidebar}/>
       <Content> {children}
       </Content>
      </div>

      <Footer/>
     </div>

    </Layout>
   ) : (

    <div className='bg-slate-700 flex min-vh-100 items-center justify-center'>

     <img
      src='./loading.gif'
      className='w-1/2 mx-auto'
      alt='loading'
     />

    </div>
   )}
  </Fragment>
 );

}

export default PageLayout