import {Layout} from "antd";
import Head from "next/head";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import {Fragment, useState, useEffect} from "react";
import {Page404} from "@/components/404";
import {useSelector, useDispatch} from "react-redux";
import {login} from "@/store/slice/user";
import {useRouter} from "next/router";
const PageLayout = ({children, title = ''}) => {
 const [mobileNavsidebar, setMobileNavsidebar] = useState(false);
 const [users, setUsers] = useState(true);
 const {Content} = Layout;
 const dispatch = useDispatch();
const router = useRouter();

 useEffect(() => {
  const user = JSON.parse(localStorage.getItem('data'))
  if (user) {
   setUsers(true)
   dispatch(login({isLoggedIn: true, user: user}))
  } else {
   setUsers(false)
   dispatch(login({isLoggedIn: false, user: null}))
   localStorage.removeItem('data')
   router.push('/login')
  }
 }, [])

 return (
  <Fragment>
   {users ? (
    <Layout>
     <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
     </Head>

     <div className="flex bg-gray-100 min-h-screen relative">

      <Sidebar mobileNavsidebar={mobileNavsidebar}/>

      <div className="flex-grow text-gray-800">
       <Header mobileNavsidebar={mobileNavsidebar} setMobileNavsidebar={setMobileNavsidebar}/>
       <Content> {children}
       </Content>
      </div>

      <Footer/>
     </div>

    </Layout>
   ) : (

    <Page404/>
   )}
  </Fragment>
 );

}

export default PageLayout